app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: Lam Nguyen

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: localhost
      port: 5432
      user: backstage
      password: backstage
integrations:
  github:
    - host: github.com

      token: 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


techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  environment: development
  providers:
    github:
      development:
        clientId: 0315870949ad6075ac9f
        clientSecret: 4f5a963cd56d51398caa8704e53ff0a93cc81c47

scaffolder:
  defaultAuthor:
    name: Lam Nguyen
    email: vanlamnguyen2110@gmail.com
  defaultCommitMessage: "Commit from Backstage"
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    - type: file
      target: ../../examples/entities.yaml

    - type: url
      target: https://github.com/alternativevn/my-backstage-templates/blob/main/GitHub%20CI/template.yaml

    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

    - type: url
      target: https://github.com/alternativevn/software-templates/blob/main/scaffolder-templates/create-react-app/template.yaml
      rules:
        - allow: [Template]

    - type: url
      target: https://github.com/alternativevn/software-templates/blob/main/scaffolder-templates/pull-request/template.yaml
      rules:
        - allow: [Template]

    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
    #   rules:
    #     - allow: [User, Group]
